[vc] Revert table splits (#796)
This reverts commit 8db9d5d41797a9793ae01e61dc03a1f4286ddbb1.

#### Type of change

- Bug fix
 
#### Description

Our CI is frequently failing during initial table creation due to errors
related to table splitting.
```
ERROR: Invalid table definition: Error creating table sc_unit_tests_db_yugabyte_faedd46f_33ee_4a6f_a190_6ef6e4ca797f.tx_status on the master: The requested number of tablet replicas (120) would cause the total running tablet replica count (1453) to exceed the safe system maximum (544) (SQLSTATE XX000)
```

While a thorough investigation into table splitting strategies and their
performance impact is necessary, this PR reverts the commit that
introduced table splits in the table creation cmd to unblock the CI.

#### Additional details (Optional)

We need to evaluate different approaches—manual splitting, automatic
splitting, and defining splits at table creation (see [YugabyteDB Tablet
Splitting
Docs](https://docs.yugabyte.com/preview/architecture/docdb-sharding/tablet-splitting/))—to
determine the optimal strategy for our use case.

#### Related issues

Resolves 
   - #795 
   - #775

Signed-off-by: Senthil Nathan N <snatara7@in.ibm.com>